spring.datasource.url: jdbc:mysql://192.168.2.77:3306/tasksDatabase
spring.datasource.username: sa
spring.datasource.password: '@Superx15616729'
spring.jpa.hibernate.ddl-auto: none
someParameter:
  value: 5463